### ISSUE TITLE
Ghost framework 

### ISSUE THREAD

**Issue by jaat1628** [jaykali/ghost#5]
Ghost framework failed to connect id address 
I tried many ip address to connect but it seems failed to connect.  Please help to solve this issue 🙏

**Comment by enty8080** [comment]
@jaat1628 

This is old and out-dated version of Ghost Framework.

Use fixed and updated version here - https://github.com/EntySec/Ghost

New one can be installed using this command:

```
pip3 install git+https://github.com/EntySec/Ghost
```
